Dev2
Nastyshka14/birthday-notification-app pull request #3
Opened 2022-08-29 07:34 UTC by Nastyshka14

2022-08-29 07:52 UTC, Nastyshka14 reviewed
everything is fixed

2022-08-29 12:01 UTC, s-severin requested changes

2022-08-29 12:01 UTC, s-severin commented on calendar/README.md
Remove this file

2022-08-29 12:01 UTC, s-severin commented on README.md
>  # Birthday notifications app
Fix file description

2022-08-29 12:01 UTC, s-severin commented on calendar/src/App.css
> -.App {
Remove empty file

2022-08-29 12:01 UTC, s-severin commented on calendar/src/App.tsx
> +    <div className="container">
Removce unused class names

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +import { useCallback } from "react";
Fix imports order

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
>  moment.updateLocale("en", { week: { dow: 1 } });
Move to separate config const file
(app/contants/moment.ts)

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
>    date: string;
https://stackoverflow.com/questions/45485073/how-do-i-express-a-date-type-in-typescript

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
>  interface ListDataItem {
`interface ListDataItem = Array<BirthdayItem>`

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +    const args = {
Add TS description for const

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +    const args = {
`const args: CalendarNotification = {`

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
>      const listData: ListDataItem[] = [];
const listData: ListDataItem

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +        element.date === moment(value.format("YYYY-MM-DD")).toISOString(true)
move to const `moment(value.format("YYYY-MM-DD")).toISOString(true)`

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +        item.date === moment(moment().format("YYYY-MM-DD")).toISOString(true)
To other one const `moment(moment().format("YYYY-MM-DD")).toISOString(true)`

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +    birthdays.forEach((item: BirthdayItem) => {
birthdays -> listData

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +        {listData.map((item: ListDataItem) => (
listData check length

2022-08-29 12:01 UTC, s-severin commented on calendar/src/components/Calendar/CalendarPage.tsx
> +    <div className="calendar">
Add styles

2022-08-29 12:01 UTC, s-severin commented on calendar/src/setupTests.js
>  import '@testing-library/jest-dom';
Add some test

2022-08-29 12:01 UTC, s-severin commented on calendar/src/useContentful.tsx
> +  date: string;
Date

2022-08-29 12:01 UTC, s-severin commented on calendar/src/useContentful.tsx
> +  birthdaysCollection {
![image](https://user-images.githubusercontent.com/10028109/187193735-a3627722-d813-430e-b0ea-d2d0e2e576aa.png)

2022-08-29 12:01 UTC, s-severin commented on calendar/src/useContentful.tsx
> +            Authorization: "Bearer L482r6IOCJjaooW7x2WDVsyi4XOVy5cHWlFmINREF9w",
TOKEN TO .ENV

2022-08-29 12:01 UTC, s-severin commented on calendar/src/useContentful.tsx
> +          return data.birthdaysCollection.items;
Check if not have birthdaysCollection or items

2022-08-29 12:01 UTC, s-severin commented on calendar/tsconfig.json
> +    "allowJs": true
"allowJs": false

2022-09-02 13:37 UTC, Nastyshka14 commented on calendar/README.md
Done

2022-09-02 13:37 UTC, Nastyshka14 commented on README.md
>  # Birthday notifications app
Done

2022-09-02 13:37 UTC, Nastyshka14 commented on calendar/src/App.css
> -.App {
Done

2022-09-02 13:38 UTC, Nastyshka14 commented on calendar/src/App.tsx
> +    <div className="container">
Done

2022-09-02 13:41 UTC, Nastyshka14 commented on calendar/src/components/Calendar/CalendarPage.tsx
> +import { useCallback } from "react";
Done rearranged
But forgot what to do with moment.js😏

2022-09-02 13:41 UTC, Nastyshka14 commented on calendar/src/useContentful.tsx
> +  date: string;
Done

2022-09-02 13:45 UTC, Nastyshka14 commented on calendar/src/useContentful.tsx
> +  birthdaysCollection {
Moved to a constant
But I could not rename it

2022-09-02 13:45 UTC, Nastyshka14 commented on calendar/src/useContentful.tsx
> +            Authorization: "Bearer L482r6IOCJjaooW7x2WDVsyi4XOVy5cHWlFmINREF9w",
Done

2022-09-02 13:47 UTC, Nastyshka14 commented on calendar/src/useContentful.tsx
> +          return data.birthdaysCollection.items;
Done

2022-09-02 13:47 UTC, Nastyshka14 commented on calendar/tsconfig.json
> +    "allowJs": true
Done

2022-10-07 13:22 UTC, closed without merging