Shultsedu 1489
Nastyshka14/birthday-notification-app pull request #5
Opened 2022-10-06 10:49 UTC by Nastyshka14

2022-10-06 14:03 UTC, PodshyvalovaRuslana requested changes

2022-10-06 14:03 UTC, PodshyvalovaRuslana commented on src/components/Calendar/CalendarPage.tsx
> +                  <div className='content__item_name'>
it's better to give the names for elements with dashes between words to make them more readable, in this case will be .content__item-name

2022-10-06 14:03 UTC, PodshyvalovaRuslana commented on src/components/Calendar/CalendarPage.tsx
> +                  <li key={item.name}>
please give more unique value for key

2022-10-06 14:03 UTC, PodshyvalovaRuslana commented on src/components/Sprites/Sprites.tsx
> +
please change the logic of component to avoid multiple function creation

2022-10-07 08:01 UTC, PodshyvalovaRuslana approved these changes

2022-10-07 08:01 UTC, PodshyvalovaRuslana commented on src/components/Sprites/Sprites.tsx
> +  const smsUrl = `sms:?body=Today is ${item}`
you also can make it like an object instead of bunch of constants, for make it more readable

2022-10-07 09:59 UTC, s-severin requested changes

2022-10-07 09:59 UTC, s-severin commented on cordovaApp/www/index.js
> +    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
Remove console.log

2022-10-07 09:59 UTC, s-severin commented on cordovaApp/www/js/index.js
> +    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
Remove console.log

2022-10-07 09:59 UTC, s-severin commented on public/index.js
> +    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
Remove

2022-10-07 09:59 UTC, s-severin commented on src/api/utils/getBirthdaysData.ts
> +            todayBirthdaysList.find((element: IBirthdayItem) => {
Move to variable

2022-10-07 09:59 UTC, s-severin commented on src/api/utils/getBirthdaysData.ts
> +              return element.name !== item.name && element.date !== item.date
todayBirthdaysList.find((element: IBirthdayItem) => element.name !== item.name && element.date !== item.date

2022-10-07 09:59 UTC, s-severin commented on src/api/utils/getBirthdaysData.ts
> +              return element.name !== item.name && element.date !== item.date
И деструктуризируй для читаемости

2022-10-07 09:59 UTC, s-severin commented on src/components/Calendar/CalendarPage.scss
> +  height: 1.4em;
Why `em`?

2022-10-07 09:59 UTC, s-severin commented on src/components/Notification/Notification.scss
> +  height: 1.4em;
Use px

2022-10-07 09:59 UTC, s-severin commented on src/hooks/useContentful.ts
>        const data = response.text()
`return response.text()`

2022-10-07 12:50 UTC, s-severin approved these changes

2022-10-07 12:50 UTC, merged